name: Cancel previous runs

on:
  workflow_dispatch:
  schedule:
    # Once every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  autocancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: Homebrew/actions/cancel-previous-runs@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          workflow: tests.yml
          event: pull_request
